version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "15433:5432"
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend
volumes:
  db-data:

networks:
  backend:
    driver: bridge
