name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup environment and install dependencies
        run: |
          apt-get update && apt-get install -y protobuf-compiler
          npm ci
      
      - name: Generate proto files
        run: npm run generate-proto
      
      - name: Run tests
        run: npm run test:coverage
